[package]
authors = ["us"]
description = "Compiled web language based on CSS syntax"
license = "MIT"
name = "cascading-wasm-language"
repository = "https://github.com/thisminute/cascading-wasm-language"
version = "0.0.2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "1.0", features = ["nightly"]}
quote = "1.0"

[dependencies.syn]
features = [
  "extra-traits",
  "full",
  "parsing",
  "printing",
  "visit-mut",
]
version = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"

[dev-dependencies.web-sys]
features = [
  "console",
  "CssStyleDeclaration",
  "CssStyleSheet",
  "Document",
  "Element",
  "Event",
  "EventListener",
  "EventTarget",
  "HtmlCollection",
  "HtmlElement",
  "HtmlHeadElement",
  "Location",
  "Node",
  "NodeList",
  "Window",
]
version = "0.3"
