[package]
name = "cwf"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
syn = { version = "1.0", features = ["extra-traits", "full", "visit-mut", "parsing"] }
quote = "1.0"
fs = "0.0"

[dev-dependencies]
create-cwf-app = { path = "./create-cwf-app" }
wasm-bindgen-test = "0.3.0"
wasm-bindgen = "0.2"

[dev-dependencies.web-sys]
version = "0.3"
features = [
  'CssStyleDeclaration',
  'CssStyleSheet',
  'Document',
  'Element',
  'Event',
  'EventListener',
  'EventTarget',
  'HtmlElement',
  'HtmlHeadElement',
  'Node',
  'Window',
]
