[package]
name = "cwf-server"
version = "0.1.0"
authors = ["us"]
description = "Compiled web framework based on CSS syntax"
repository = "github.com/thisminute/cwf"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
proc-macro2 = { version = "1.0", features = ["nightly"] }
syn = { version = "1.0", features = ["extra-traits", "full", "visit-mut", "parsing"] }
quote = "1.0"
cwf = { path = "cwf" }

[dependencies.web-sys]
version = "0.3.40"
features = [
  'console',
  'CssStyleDeclaration',
  'Document',
  'Element',
  'HtmlElement',
  'HtmlHeadElement',
  'Node',
  'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1" }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
