[package]
name = "cwf-rust"
version = "0.1.0"
authors = ["us"]
description = "Web framework based on CSS syntax"
repository = "github.com/thisminute/cwf"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.37"
features = [
  'console',
  'Document',
  'Element',
  'HtmlElement',
  'HtmlHeadElement',
  'Node',
  'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1" }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
