[package]
authors = ["us"]
description = "Compiled web language based on CSS syntax"
license = "MIT"
name = "cascading-wasm-language"
repository = "https://github.com/thisminute/cascading-wasm-language"
version = "0.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
quote = "1.0"
fs = "0.0"

[dependencies.syn]
version = "1.0"
features = [
  'extra-traits',
  'full',
  'parsing',
  'printing',
  'visit-mut',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
wasm-bindgen = "0.2"

[dev-dependencies.web-sys]
version = "0.3"
features = [
  'CssStyleDeclaration',
  'CssStyleSheet',
  'Document',
  'Element',
  'Event',
  'EventListener',
  'EventTarget',
  'HtmlElement',
  'HtmlHeadElement',
  'Location',
  'Node',
  'Window',
]
