name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: cargo install wasm-pack
    - name: Build
      run: cargo build --verbose
    - name: Run tests (chrome)
      run: wasm-pack test --release --headless --chrome -- --jobs 1
