name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: cargo install wasm-pack 
    - name: Run tests (CLI)
      run: cargo test --target wasm32-unknown-unknown --verbose
    - name: Run tests (chrome)
      run: wasm-pack test --chrome
    - name: Run tests (firefox)
      run: wasm-pack test --headless --firefox
    - name: Build
      run: cargo build --verbose 
